version: '3'

services:
  nethunter-kernel-build:
    build:
      context: nethunter-kernel-build
      args:
        - TOOLCHAIN_BRANCH=oreo-release
        - TOOLCHAIN_REPO=https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9
    tty: true
    stdin_open: true
    volumes:
    - ./src:/src
    command: /bin/bash
